@startuml
class UpdateProductCommandHandler <<sealed>> {
    + Handle(request:UpdateProductCommand, cancellationToken:CancellationToken) : Task<Result>
    - OnSuccess(request:UpdateProductCommand, user:User) : Func<Product, Task<Result>>
    - {static} UpdateProduct(product:Product, newName:string, macronutrients:Macronutrients, user:User) : Func<Result>
}
class "ILogger`1"<T> {
}
class "IRequestHandler`2"<T1,T2> {
}
"IRequestHandler`2" "<UpdateProductCommand,Result>" <|-- UpdateProductCommandHandler
UpdateProductCommandHandler o-> "productRepository" IProductRepository
UpdateProductCommandHandler o-> "logger<UpdateProductCommandHandler>" "ILogger`1"
@enduml
