version: '3.4'

networks:
  app-product:
    name: app-product

services:
  product.mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: secret
    container_name: product.mysql
    volumes:
      - ./mysql/sql/init-mysql-product.sql:/docker-entrypoint-initdb.d/1.sql
    networks:
      - app-product
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - product.mysql
    environment:
      PMA_HOST: product.mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - app-product
    restart: always
    depends_on:
      - product.mysql
    ports:
      - 8081:80

  product.cassandra:
    image: cassandra:latest
    container_name: cassandra-product
    networks:
      - app-product
    ports:
      - 9042:9042
    expose:
      - 9042
    volumes:
      - ./cassandra/config/cassandra.yaml:/etc/cassandra/cassandra.yaml

  product.cassandra-init:
    image: cassandra:latest
    container_name: product.cassandra-init
    networks:
      - app-product
    depends_on:
      - product.cassandra
    volumes:
      - ./cassandra/sql:/dump/
    command: /bin/bash -c "sleep 60 && cqlsh product.cassandra -u cassandra -p cassandra -f /dump/init-cassandra-product.sql"

  propernutritiondiary.product.api:
    image: ${DOCKER_REGISTRY-}propernutritiondiaryproductapi
    build:
      context: .
      dockerfile: src/Product/ProperNutritionDiary.Product.Api/Dockerfile

  propernutritiondiary.user.api:
    image: ${DOCKER_REGISTRY-}propernutritiondiaryuserapi
    build:
      context: .
      dockerfile: src/User/ProperNutritionDiary.User.Api/Dockerfile

