version: "3.4"

networks:
  app:

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: secret
    container_name: mysql
    networks:
      - app
    ports:
      - "3306:3306"
    expose:
      - "3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      - app
    restart: always
    depends_on:
      - mysql
    ports:
      - 8081:80

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    networks:
      - app
    ports:
      - 9042:9042
    expose:
      - 9042
    volumes:
      - ./cassandra/config/cassandra.yaml:/etc/cassandra/cassandra.yaml

  cassandra-init:
    image: cassandra:latest
    container_name: cassandra-init
    networks:
      - app
    depends_on:
      - cassandra
    volumes:
      - ./cassandra/sql:/dump/
    command: /bin/bash -c "sleep 60 && cqlsh cassandra -u cassandra -p cassandra -f /dump/init-cassandra-product.sql"
