@startuml
class MacronutrientsTest {
    + SumOfTwoMacronutrients_ShouldReturnSumOfLeftAndRight() : void
}
MacronutrientsTest o-> "left" Macronutrients
MacronutrientsTest o-> "right" Macronutrients
@enduml
