@startuml
class ProductFavoriteServiceTest {
    + ProductFavoriteServiceTest()
    + <<async>> AddToFavoriteList_ShouldFailed_WhenUserIsAdmin() : Task
    + <<async>> AddToFavoriteList_ShouldFailed_WhenProductAlreadyInFavoriteList() : Task
    + <<async>> AddToFavoriteList_ShouldSuccess_WhenOk() : Task
}
ProductFavoriteServiceTest --> "productFavoriteService" ProductFavoriteService
ProductFavoriteServiceTest --> "productRepository" IProductRepository
ProductFavoriteServiceTest --> "eventDispatcher" IEventDispatcher
ProductFavoriteServiceTest o-> "adminUser" User
ProductFavoriteServiceTest o-> "plainUser" User
ProductFavoriteServiceTest --> "testProduct" Product
@enduml
