@startuml
class ProductTest {
    - <<const>> name : string = "ProductTestName"
    + CreateProduct_MustReturnFailed_WhenNameIsNullOrEmpty() : void
    + CreateProduct_MustReturnSuccessAndRaiseEvent_WhenOk() : void
    + UpdateProduct_MustReturnFailed_WhenUpdateSystemProductWithNotAdminUpdater() : void
    + RemoveProduct_MustReturnFailed_WhenRemoveSystemProductWithNotAdminUpdater() : void
    + RemoveProduct_MustReturnFailed_WhenRemoveProductWithNoOwner() : void
    + RemoveProduct_MustReturnFailed_WhenRemoveProductInFavoriteList() : void
    + RemoveProduct_MustReturnSuccess_WhenOk() : void
    + UpdateProduct_MustReturnFailed_WhenUpdateProductWithNoOwner() : void
    + UpdateProduct_MustReturnFailed_WhenUpdateProductWithNullOrEmptyName() : void
    + UpdateProduct_MustReturnSuccessAndRaiseEvent_WhenProductUpdateOk() : void
}
ProductTest o-> "productId" ProductId
ProductTest o-> "createdAt" DateTime
ProductTest o-> "updatedAt" DateTime
ProductTest o-> "macronutrients" Macronutrients
ProductTest o-> "plainUser" User
ProductTest o-> "adminUser" User
ProductTest o-> "anotherPlainUser" User
@enduml
