@startuml
class ProductSnapshot {
    + Name : string <<get>> <<set>>
    + FromExternalSource : bool <<get>> <<set>>
    + ExternalSource : string? <<get>> <<set>>
}
ProductSnapshot --> "Id" Guid
ProductSnapshot o-> "Macronutrients" MacronutrientsSnapshot
ProductSnapshot --> "Owner" Guid
ProductSnapshot --> "ExternalSourceType" ExternalSourceType
ProductSnapshot --> "CreatedAt" DateTime
ProductSnapshot --> "UpdatedAt" DateTime
@enduml
