// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProperNutritionDiary.UserStatsApi.Db;

#nullable disable

namespace ProperNutritionDiary.UserStatsApi.Migrations
{
    [DbContext(typeof(AppCtx))]
    [Migration("20240620020416_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProperNutritionDiary.UserStatsApi.DynamicUserStats.DynamicUserStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DynamicUserStats");
                });

            modelBuilder.Entity("ProperNutritionDiary.UserStatsApi.StaticUserStats.StaticUserStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LifeStyle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StaticUserStats");
                });

            modelBuilder.Entity("ProperNutritionDiary.UserStatsApi.UserTotalDailiesStats.UserTotalDailiesStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalWeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TotalDailiesStats");
                });

            modelBuilder.Entity("ProperNutritionDiary.UserStatsApi.UserTotalDailiesStats.UserTotalDailiesStats", b =>
                {
                    b.OwnsOne("ProperNutritionDiary.BuildingBlocks.ProductGlobals.Macronutrients.Macronutrients", "TotalMacronutrients", b1 =>
                        {
                            b1.Property<Guid>("UserTotalDailiesStatsId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Calories")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Calories");

                            b1.Property<decimal>("Carbohydrates")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Carbohydrates");

                            b1.Property<decimal>("Fats")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Fats");

                            b1.Property<decimal>("Proteins")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Proteins");

                            b1.HasKey("UserTotalDailiesStatsId");

                            b1.ToTable("TotalDailiesStats");

                            b1.WithOwner()
                                .HasForeignKey("UserTotalDailiesStatsId");
                        });

                    b.Navigation("TotalMacronutrients")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
