@startuml
class CreateProductCommand <<sealed>> <<record>> {
    + UserId : Guid? <<get>> <<init>>
    + ProductName : string <<get>> <<init>>
    + Calories : decimal <<get>> <<init>>
    + Proteins : decimal <<get>> <<init>>
    + Fats : decimal <<get>> <<init>>
    + Carbohydrates : decimal <<get>> <<init>>
}
class "IRequest`1"<T> {
}
"IRequest`1" "<Result<Guid>>" <|-- CreateProductCommand
CreateProductCommand --> "UserRole" UserRole
@enduml
