@startuml
class RemoveProductCommand <<sealed>> <<record>> {
}
class "IRequest`1"<T> {
}
"IRequest`1" "<Result>" <|-- RemoveProductCommand
RemoveProductCommand --> "UserId" Guid
RemoveProductCommand --> "UserRole" UserRole
RemoveProductCommand --> "ProductId" Guid
@enduml
