@startuml
class RemoveProductCommandHandler <<sealed>> {
    + <<async>> Handle(request:RemoveProductCommand, cancellationToken:CancellationToken) : Task<Result>
}
class "ILogger`1"<T> {
}
class "IRequestHandler`2"<T1,T2> {
}
"IRequestHandler`2" "<RemoveProductCommand,Result>" <|-- RemoveProductCommandHandler
@enduml
