@startuml
class ProductSummarySnapshot {
    + Name : string <<get>> <<set>>
    + ExternalSource : string? <<get>> <<set>>
    + ViewCount : int <<get>> <<set>>
    + AddCount : int <<get>> <<set>>
}
ProductSummarySnapshot --> "Id" Guid
ProductSummarySnapshot o-> "Macronutrients" MacronutrientsSnapshot
ProductSummarySnapshot --> "ExternalSourceType" ExternalSourceType
ProductSummarySnapshot --> "Owner" Guid
@enduml
