@startuml
class NoSqlConnectionProvider {
    - <<readonly>> keySpace : string
    + Get() : Task<IMapper>
}
INoSqlConnectionProvider <|-- NoSqlConnectionProvider
NoSqlConnectionProvider o-> "cluster" Cluster
@enduml
