@startuml
class GetProductByIdQuery <<sealed>> <<record>> {
}
class "IRequest`1"<T> {
}
"IRequest`1" "<ProductSummary?>" <|-- GetProductByIdQuery
GetProductByIdQuery --> "ProductId" Guid
GetProductByIdQuery --> "UserId" Guid
GetProductByIdQuery --> "UserRole" UserRole
@enduml
