@startuml
class GetProductListHandlerTest {
    + GetProductListHandlerTest()
    + <<async>> Handle_MustExec() : Task
}
GetProductListHandlerTest --> "productRepository" IProductSummaryRepository
GetProductListHandlerTest --> "eventDispatcher" IEventDispatcher
GetProductListHandlerTest --> "handler" GetProductListHandler
GetProductListHandlerTest --> "productSummary" ProductSummary
GetProductListHandlerTest --> "query" GetProductList
GetProductListHandlerTest o-> "user" User
@enduml
